### ISSUE TITLE
NameError: name 'long' is not defined

### ISSUE THREAD

**Issue by adamcho14** [blockstack/secret-sharing#26]
This is what I get:
```
Traceback (most recent call last):
  File "/Users/Adam/PycharmProjects/SEVAS/local/key_management.py", line 5, in <module>
    from secretsharing import PlaintextToHexSecretSharer
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/secretsharing/__init__.py", line 12, in <module>
    from .sharing import *
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/secretsharing/sharing.py", line 14, in <module>
    from .primes import get_large_enough_prime
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/secretsharing/primes.py", line 35, in <module>
    STANDARD_PRIMES = calculate_mersenne_primes() + [
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/secretsharing/primes.py", line 25, in calculate_mersenne_primes
    prime = long(1)
NameError: name 'long' is not defined
```

**Comment by konchunas** [comment]
Newest package with fix for this is not deployed onto pip repo, but you can install directly from github by using
`pip install git+https://github.com/blockstack/secret-sharing`

**Comment by vis7** [comment]
I upgraded by above link but it still does not resolve error

**Comment by michaelbarbas** [comment]
> 
> 
> I upgraded by above link but it still does not resolve error

hey @vis7 you ever resolve that issue??

**Comment by DoubleD0u** [comment]
I'm ok!

**Comment by rstyczynski** [comment]
Hi. FYI On already installed package force is required.

`pip3 install --upgrade --force-reinstall  git+https://github.com/blockstack/secret-sharing`
